In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator


In [2]:
img_size = (128, 128)      
batch_size = 32
train_dir = 'train/'
test_dir = 'test/'

In [ ]:
import pandas as pd
import os

test_filenames = os.listdir(test_dir)
test_df = pd.DataFrame({'filename': test_filenames})


In [16]:
train_datagen = ImageDataGenerator(rescale=1./255, validation_split= 0.2)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory( train_dir, target_size=img_size, batch_size=batch_size, 
                                                    class_mode='categorical', subset='training', shuffle=True)

val_generator = train_datagen.flow_from_directory( train_dir, target_size=img_size, batch_size=batch_size, 
                                                  class_mode='categorical', subset='validation', shuffle=True)

test_generator = test_datagen.flow_from_dataframe(dataframe=test_df, directory=test_dir, x_col='filename',y_col=None,
                                                  target_size=img_size, batch_size=batch_size, class_mode=None, shuffle=False)


print(train_generator.class_indices)


Found 2198 images belonging to 5 classes.
Found 548 images belonging to 5 classes.
Found 924 validated image filenames.
{'daisy': 0, 'dandelion': 1, 'rose': 2, 'sunflower': 3, 'tulip': 4}


In [17]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape = (128, 128, 3)), 
    
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    
    tf.keras.layers.Conv2D(64, (3, 3), activation = 'relu'), 
    tf.keras.layers.MaxPooling2D((2, 2)),
    
    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(5, activation='softmax'),
    
    ])
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_6 (Conv2D)               │ (None, 126, 126, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_6 (MaxPooling2D)  │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 61, 61, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_7 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 28, 28, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_8 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 25088)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 128)            │     3,211,392 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 5)              │           645 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,305,285 (12.61 MB)

 Trainable params: 3,305,285 (12.61 MB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_6 (Conv2D)               │ (None, 126, 126, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_6 (MaxPooling2D)  │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 61, 61, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_7 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 28, 28, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_8 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 25088)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 128)            │     3,211,392 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 5)              │           645 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,305,285 (12.61 MB)

 Trainable params: 3,305,285 (12.61 MB)

 Non-trainable params: 0 (0.00 B)

In [22]:
history = model.fit(train_generator, validation_data=val_generator, epochs=10)

Epoch 1/10
69/69 ━━━━━━━━━━━━━━━━━━━━ 33s 479ms/step - accuracy: 0.5140 - loss: 1.1304 - val_accuracy: 0.5219 - val_loss: 1.1772
Epoch 2/10
69/69 ━━━━━━━━━━━━━━━━━━━━ 30s 440ms/step - accuracy: 0.6189 - loss: 0.9909 - val_accuracy: 0.6131 - val_loss: 1.0144
Epoch 3/10
69/69 ━━━━━━━━━━━━━━━━━━━━ 44s 475ms/step - accuracy: 0.6927 - loss: 0.8370 - val_accuracy: 0.6350 - val_loss: 1.0219
Epoch 4/10
69/69 ━━━━━━━━━━━━━━━━━━━━ 35s 510ms/step - accuracy: 0.7415 - loss: 0.6530 - val_accuracy: 0.6277 - val_loss: 1.0274
Epoch 5/10
69/69 ━━━━━━━━━━━━━━━━━━━━ 36s 520ms/step - accuracy: 0.8130 - loss: 0.5134 - val_accuracy: 0.6040 - val_loss: 1.0431
Epoch 6/10
69/69 ━━━━━━━━━━━━━━━━━━━━ 35s 514ms/step - accuracy: 0.8607 - loss: 0.3825 - val_accuracy: 0.6131 - val_loss: 1.2040
Epoch 7/10
69/69 ━━━━━━━━━━━━━━━━━━━━ 35s 509ms/step - accuracy: 0.8927 - loss: 0.2951 - val_accuracy: 0.6186 - val_loss: 1.2790
Epoch 8/10
69/69 ━━━━━━━━━━━━━━━━━━━━ 35s 502ms/step - accuracy: 0.9438 - loss: 0.1761 - val_accu

In [ ]:
prediction = model.predict(test_generator)
print(f'test predict: {prediction}')


29/29 ━━━━━━━━━━━━━━━━━━━━ 5s 172ms/step
test predict: [[3.3525903e-06 2.3149026e-07 5.1755836e-07 9.9957520e-01 4.2074570e-04]
 [7.7775638e-03 9.7400475e-01 8.5997013e-03 1.3923442e-03 8.2255509e-03]
 [7.8306311e-01 7.0122619e-10 1.0745508e-03 1.8479487e-01 3.1067420e-02]
 ...
 [1.7426604e-02 9.8089004e-01 2.9155053e-04 2.5010690e-06 1.3893330e-03]
 [1.8865471e-04 5.9214526e-05 1.6886046e-06 9.9825329e-01 1.4970693e-03]
 [3.7418667e-06 6.3840275e-07 5.6361736e-05 9.9967861e-01 2.6069232e-04]]


In [26]:
import numpy as np
predicted_classes = np.argmax(prediction, axis=1)


In [27]:
print(predicted_classes[:10])


[3 1 0 0 0 0 4 3 3 3]


In [30]:
index_to_class = {v: k for k, v in train_generator.class_indices.items()}


In [31]:
predicted_labels = [index_to_class[i] for i in predicted_classes]


In [32]:
print(predicted_labels[:10])

['sunflower', 'dandelion', 'daisy', 'daisy', 'daisy', 'daisy', 'tulip', 'sunflower', 'sunflower', 'sunflower']


In [35]:
import pandas as pd
import os
from tensorflow.keras.preprocessing import image
import numpy as np

In [ ]:
predicted_labels = [labels_map[i] for i in predicted_classes]

df = pd.read_csv("Testing_set_flower (1).csv")

df['Predicted_Label'] = predicted_labels

print(df.head(10))

       filename Predicted_Label
0   Image_1.jpg       sunflower
1   Image_2.jpg       dandelion
2   Image_3.jpg           daisy
3   Image_4.jpg           daisy
4   Image_5.jpg           daisy
5   Image_6.jpg           daisy
6   Image_7.jpg           tulip
7   Image_8.jpg       sunflower
8   Image_9.jpg       sunflower
9  Image_10.jpg       sunflower


In [51]:
df.to_csv("flower_predictions.csv", index=False)
